--- #YAML:1.0
name:               courgette
version:            0.1
abstract:           ~
author:
    - Stephen Hardisty <moowahaha@hotmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:    1.13
    Getopt::Long:  2.37
    Test::More:    0.86
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
